apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-service
  labels:
    app: trading-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-service
  template:
    metadata:
      labels:
        app: trading-service
    spec:
      containers:
      - name: trading-service
        image: trading-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        env:
        - name: PORTFOLIO_SERVICE_URL
          value: "http://portfolio-service:8001"
